version: "3.8"

services:
  ollama-proxy:
    build: .
    container_name: ollama-proxy
    env_file:
      - .env
    ports:
      - "${BIND_ADDRESS}:5000:5000"
    networks:
      - internal
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ollama.rule=Host(`${OLLAMA_HOST}`)"
      - "traefik.http.routers.ollama.entrypoints=web"
      - "traefik.http.services.ollama.loadbalancer.server.port=5000"
      - "traefik.http.services.ollama.loadbalancer.healthcheck.path=${HEALTH_PATH}"
      - "traefik.http.services.ollama.loadbalancer.healthcheck.interval=10s"
    volumes:
      - ./config/servers.yml:/app/config/servers.yml:ro
    restart: unless-stopped

networks:
  # When services reference "web", they use the external network specified by TRAEFIK_NETWORK
  web:
    external: true
    name: "${TRAEFIK_NETWORK}"

  # internal: uses the default bridge driver
  internal:
    driver: bridge
